# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Simple, fast and user-friendly alternative to 'find'
brew "fd"
# Modern, maintained replacement for ls
brew "eza"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Simple terminal UI for git commands
brew "lazygit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment, needed for neovim lsp
brew "node@24"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
